// Single source of truth for all business information (NAP consistency)
export const BUSINESS = {
  name: 'Nonstop Lock & Key',
  legalName: 'Nonstop Lock & Key',
  phone: '(314) 532-1112',
  phoneTel: 'tel:+13145321112',
  phoneRaw: '+13145321112',
  email: 'Nonstoplockandkeyco@gmail.com',
  url: 'https://nonstoplockandkey.com',
  logo: 'https://nonstoplockandkey.com/nonstop-lock-and-key-st-louis-locksmith-logo-no-bg-final-cut.png',
  logoPath: '/nonstop-lock-and-key-st-louis-locksmith-logo-no-bg-final-cut.png',
  priceRange: '$$',
  ratingValue: '5.0',
  reviewCount: '100',
  streetAddress: '1178 Rue La Chelle Walk',
  addressCity: 'Creve Coeur',
  city: 'St. Louis',
  state: 'MO',
  stateFullName: 'Missouri',
  postalCode: '63141',
  region: 'US-MO',
  lat: 38.6270,
  lng: -90.1994,
  gbpUrl: 'https://g.page/r/CW7WyktBAIxtEBM',
  gbpReviewUrl: 'https://g.page/r/CW7WyktBAIxtEBM/review',
  social: {
    facebook: 'https://www.facebook.com/profile.php?id=61587625812146',
    instagram: 'https://www.instagram.com/nonstoplockandkey/',
    tiktok: 'https://www.tiktok.com/@saint_louis_locksmith',
    youtube: 'https://www.youtube.com/@NonstopLockAndKey',
    pinterest: 'https://www.pinterest.com/nonstoplockandkeyco/',
  },
  // Master list of profile URLs for LocalBusiness `sameAs` schema across the site.
  sameAs: [
    'https://g.page/r/CW7WyktBAIxtEBM',
    'https://www.facebook.com/profile.php?id=61587625812146',
    'https://www.instagram.com/nonstoplockandkey/',
    'https://www.tiktok.com/@saint_louis_locksmith',
    'https://www.youtube.com/@NonstopLockAndKey',
    'https://www.pinterest.com/nonstoplockandkeyco/',
  ],
} as const;
